

const cwb = [
    "CADEIA PÚBLICA DE ARAUCÁRIA - CPARAU",
    "CADEIA PÚBLICA DE CAMPO LARGO - CPCAMP",
    "CADEIA PÚBLICA DE COLOMBO - CPCOLO",
    "CADEIA PÚBLICA DE CURITIBA - CPCTBA",
    "CADEIA PÚBLICA DE GUARATUBA - CPGTBA",
    "CADEIA PÚBLICA DE PARANAGUÁ - CPPGUA",
    "CADEIA PÚBLICA DE RIO NEGRO - CPRN",
    "CASA DE CUSTÓDIA DE CURITIBA - CCC",
    "CASA DE CUSTÓDIA DE PIRAQUARA – CCP / CENTRO DE OBSERVAÇÃO CRIMINOLÓGICA E TRIAGEM – COT",
    "XXXXXXX",
    "XXXXXXX",
    "XXXXXXX",
    "XXXXXXX",
    "XXXXXXX",
    "XXXXXXX",
    "XXXXXXX",
    "XXXXXXX",
    "XXXXXXX",
    "XXXXXXX",
    
]